Repository AmericaSCORESBayArea/AmericaScores-CoachApp, pull requests merged in 2022-09, with the labels that each got.

#321 Fixed/students list
  assets/Icons/warning_Icon.png
  src/Activities.Screen.js
  src/Attendance.Screen.js
  src/components/StudentModal.component.js
Labels: bug

#318 fix: ios build on m1 with arm64 supported
  ios/AmericanScoresApp.xcodeproj/project.pbxproj
  ios/Podfile
Labels: DevOps

#325 fixes icons and Apple silicon build
  ios/AmericanScoresApp.xcodeproj/project.pbxproj
  ios/AmericanScoresApp.xcodeproj/xcshareddata/xcschemes/AmericanScoresApp.xcscheme
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-1024.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-120.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-121.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-152.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-167.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-180.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-20.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-20x20@1x.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-20x20@2x.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-20x20@3x.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-29.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-29x29@1x.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-29x29@2x.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-29x29@3x.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-30.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-40.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-40x40@2x.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-40x40@3x.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-41.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-42.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-58.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-59.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-60.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-60x60@2x.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-60x60@3x.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-76.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-76x76@1x.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-76x76@2x.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-80.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-81.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-83.5@2x.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-87.png
  ios/AmericanScoresApp/Images.xcassets/AppIcon.appiconset/Icon-marketing-1024x1024.png
  ios/Podfile.lock
  src/Activities.Screen.js
  src/components/StudentModal.component.js
Labels: DevOps, Critical

#331 Fix/headcount modal
  src/Attendance.Screen.js
Labels: bug
